### ISSUE TITLE
Duplication is throwing an error on save

### ISSUE THREAD

**Issue by aschrammel** [AmastyLtd/promotions-manager-for-magento-2#2]
# Preconditions (*)
* Adobe Commerce 2.4.4-p6
* PHP 8.1

# Steps to reproduce (*)
* Go to `Admin --> Marketing --> Cart Price Rules`
* `Duplicate` an existing rule
* Save duplicated rule

# Expected result (*)
The duplicated and adjusted rule is saved

# Actual result (*)
Rule is not saved with the error message `Something went wrong while saving the rule data. Please review the error log.`

The error log reveals following error:
```Exception: Invalid input date format 'Invalid date' in /srv/vendor/magento/framework/Stdlib/DateTime/Filter/Date.php:70
Stack trace:
#0 /srv/vendor/magento/zendframework1/library/Zend/Filter.php(114): Magento\Framework\Stdlib\DateTime\Filter\Date->filter()
#1 /srv/vendor/magento/zendframework1/library/Zend/Filter/Input.php(722): Zend_Filter->filter()
#2 /srv/vendor/magento/zendframework1/library/Zend/Filter/Input.php(701): Zend_Filter_Input->_filterRule()
#3 /srv/vendor/magento/zendframework1/library/Zend/Filter/Input.php(785): Zend_Filter_Input->_filter()
#4 /srv/vendor/magento/zendframework1/library/Zend/Filter/Input.php(381): Zend_Filter_Input->_process()
#5 /srv/vendor/magento/module-sales-rule/Controller/Adminhtml/Promo/Quote/Save.php(86): Zend_Filter_Input->getUnescaped()
#6 /srv/vendor/magento/framework/Interception/Interceptor.php(58): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save->execute()
#7 /srv/vendor/magento/framework/Interception/Interceptor.php(138): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->___callParent()
#8 /srv/vendor/magento/framework/Interception/Interceptor.php(153): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->Magento\Framework\Interception\{closure}()
#9 /srv/generated/code/Magento/SalesRule/Controller/Adminhtml/Promo/Quote/Save/Interceptor.php(23): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->___callPlugins()
#10 /srv/vendor/magento/framework/App/Action/Action.php(111): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->execute()
#11 /srv/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#12 /srv/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#13 /srv/vendor/magento/framework/Interception/Interceptor.php(138): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->___callParent()
#14 /srv/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->Magento\Framework\Interception\{closure}()
#15 /srv/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#16 /srv/vendor/magento/framework/Interception/Interceptor.php(153): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->Magento\Framework\Interception\{closure}()
#17 /srv/generated/code/Magento/SalesRule/Controller/Adminhtml/Promo/Quote/Save/Interceptor.php(32): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->___callPlugins()
#18 /srv/vendor/magento/framework/App/FrontController.php(245): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save\Interceptor->dispatch()
#19 /srv/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#20 /srv/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#21 /srv/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#22 /srv/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#23 /srv/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /srv/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /srv/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /srv/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#27 /srv/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#28 /srv/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#29 /srv/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#30 /srv/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#31 /srv/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#32 {main}```

Problem seems to be, that the `\Amasty\Rgrid\Model\DuplicateRuleProcessor::execute` function is not resetting the `from_date` to `null`.

**Comment by aschrammel** [comment]
Closed, as repo code differs from our codebase. Seems we have a different source there.
